name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Create dist folder
        run: mkdir -p dist

      - name: Generate light snake
        uses: Platane/snk@v3
        with:
          github_user_name: IlianTheOne0
          output: dist/github-contribution-grid-snake.svg

      - name: Generate dark snake
        uses: Platane/snk@v3
        with:
          github_user_name: IlianTheOne0
          output: dist/github-contribution-grid-snake-dark.svg
          color_snake: "#00FF00"
          color_dots: "#dddbdb,#adadad,#7e7e7e,#4f4f4f,#212121"
          background: "#0d1117"
          args: --force-color

      - name: Push both versions
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
